apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: # soft limit
        cpu: "100m"
        memory: "128Mi"
      limits: # hard limit
        cpu: "150m"
        memory: "256Mi"