apiVersion: v1
kind: Service
metadata:
  name: nginx
  # servicer labels
  labels:
    project: roboshop
    environment: dev
spec:
  # Service uses the below labels to select the pods
  selector:
    project: my-app
    tier: frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx # pod name
  labels:
    project: my-app
    environment: dev
    component: frontend
    tier: frontend
spec:
  containers:
  - name: nginx # container name
    image: nginx # by default it will get from docker hub
    