apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  # servicer labels
  labels:
    project: my-project
    environment: dev
spec:
  type: LoadBalancer
  # Service uses the below labels to select the pods
  selector:
    project: my-app
    tier: frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      nodePort: 30008 #predefined