---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: MY-PROJECT
  region: us-east-1
managedNodeGroups:
  - name: MY-WORKERS
    instanceType: t3.small 
    desiredCapacity: 2
    spot: true